import type { FastingKind } from './types';
import { dayStart } from './time';

/** A festival, fast or feast. Dates for 2026-27; moon-dependent dates can be off by a day. Source: expert_reports/calendar.json. */
export interface Festival {
  id: string;
  name: string;
  community: string;
  /** Local dates, YYYY-MM-DD. */
  start: string;
  end: string;
  kind: 'fast' | 'feast' | 'mixed';
  fasting: FastingKind | null;
  eaten: string;
  avoided: string;
  confidence: string;
}

export const FESTIVALS: Festival[] = [
 {
  "id": "cal-001",
  "name": "Pitru Paksha (last days; ends Sarvapitri Amavasya Oct 10)",
  "community": "Hindu",
  "start": "2026-10-01",
  "end": "2026-10-10",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Simple satvik meals, kheer, puri, lauki, arbi, kaddu, dal; shraddha feeding",
  "avoided": "Onion, garlic, non-veg, brinjal/radish/masoor in many families; no new purchases/weddings",
  "confidence": "web-supported (Navratri Oct 11)"
 },
 {
  "id": "cal-002",
  "name": "Indira Ekadashi",
  "community": "Hindu",
  "start": "2026-10-06",
  "end": "2026-10-06",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-003",
  "name": "Sharad Navratri",
  "community": "Hindu",
  "start": "2026-10-11",
  "end": "2026-10-19",
  "kind": "fast",
  "fasting": "navratri",
  "eaten": "Sendha namak (rock salt), kuttu/singhara flour, samak rice, sabudana, makhana, potatoes, sweet potato, pumpkin, lauki, fruit, milk, curd, paneer, peanuts, ghee",
  "avoided": "Grains (wheat, rice, dals), regular salt, onion, garlic, meat, fish, egg, alcohol, (strict) turmeric-free/less spice varies",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-004",
  "name": "Durga Puja (Bengal/Odisha/Assam) - bhog, Shashthi to Dashami",
  "community": "Bengali",
  "start": "2026-10-16",
  "end": "2026-10-20",
  "kind": "feast",
  "fasting": null,
  "eaten": "Bhog khichuri, labra, begun bhaja, chutney, payesh, luchi-alur dom, fish/mutton on Saptami-Navami in many Bengali homes, sweets",
  "avoided": "Many Bengali families avoid onion-garlic only in bhog (offering); home meals often include fish",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-005",
  "name": "Jain Oli (Navpad Ayambil Oli)",
  "community": "Jain",
  "start": "2026-10-17",
  "end": "2026-10-25",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Ayambil: boiled/steamed grains, dal, bland, once a day, no oil/salt/spices in strict form",
  "avoided": "Oil, ghee, milk, curd, sugar, jaggery, vegetables, fruit, salt, spice (strict)",
  "confidence": "approx-from-tithi-(Ashwin-Shukla-7-15)"
 },
 {
  "id": "cal-006",
  "name": "Dussehra / Vijayadashami",
  "community": "Hindu",
  "start": "2026-10-20",
  "end": "2026-10-20",
  "kind": "feast",
  "fasting": null,
  "eaten": "Jalebi-fafda (Gujarat), sweets, regular meals; fast ends",
  "avoided": "",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-007",
  "name": "Papankusha Ekadashi",
  "community": "Hindu",
  "start": "2026-10-22",
  "end": "2026-10-22",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-008",
  "name": "Sharad Purnima / Kojagari Lakshmi Puja",
  "community": "Hindu",
  "start": "2026-10-25",
  "end": "2026-10-26",
  "kind": "feast",
  "fasting": null,
  "eaten": "Kheer/doodh-pauva kept in moonlight, sweets, Bengal narkel naru",
  "avoided": "",
  "confidence": "computed-astronomically-Delhi-sunrise-plus-/-1-day-regional-variation"
 },
 {
  "id": "cal-009",
  "name": "Karva Chauth",
  "community": "Hindu",
  "start": "2026-10-29",
  "end": "2026-10-29",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Pre-dawn sargi (fruit, nuts, mathri, sweets, paranthas, milk); evening break with water then full dinner (puri-sabzi, halwa)",
  "avoided": "All food and water sunrise to moonrise (nirjala)",
  "confidence": "verified (Oct 29 per web; moonrise tithi check)"
 },
 {
  "id": "cal-010",
  "name": "Rama Ekadashi",
  "community": "Hindu",
  "start": "2026-11-05",
  "end": "2026-11-05",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-011",
  "name": "Dhanteras",
  "community": "Hindu",
  "start": "2026-11-06",
  "end": "2026-11-06",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sweets, kheer, coriander-jaggery, vegetarian meals",
  "avoided": "",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-012",
  "name": "Naraka Chaturdashi / Choti Diwali",
  "community": "Hindu",
  "start": "2026-11-07",
  "end": "2026-11-07",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sweets, til/oil bath festival meals",
  "avoided": "",
  "confidence": "verified-approx"
 },
 {
  "id": "cal-013",
  "name": "Diwali (Lakshmi Puja)",
  "community": "Hindu",
  "start": "2026-11-08",
  "end": "2026-11-08",
  "kind": "feast",
  "fasting": null,
  "eaten": "Mithai (ladoo, barfi, kaju katli, gulab jamun, jalebi, soan papdi), chakli, shankarpali, karanji, murukku, namak para, poha-chivda, puri-sabzi, dal; Bengal Kali Puja; Jain Nirvan Kalyanak same night",
  "avoided": "Non-veg in most Hindu/Jain homes; Jain: no root vegetables",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-014",
  "name": "Govardhan Puja / Annakut / Gujarati New Year",
  "community": "Hindu",
  "start": "2026-11-10",
  "end": "2026-11-10",
  "kind": "feast",
  "fasting": null,
  "eaten": "Annakut of dozens of vegetarian dishes, kadhi, sweets, farsan",
  "avoided": "",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-015",
  "name": "Bhai Dooj / Bhau Beej",
  "community": "Hindu",
  "start": "2026-11-11",
  "end": "2026-11-11",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sweets, shrikhand, festive meal",
  "avoided": "",
  "confidence": "verified (some sources Nov 10)"
 },
 {
  "id": "cal-016",
  "name": "Chhath Puja",
  "community": "Hindu",
  "start": "2026-11-13",
  "end": "2026-11-16",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Nahay-khay: kaddu-bhat, chana dal, rice; Kharna: kheer-roti; thekua, fruit as prasad",
  "avoided": "Salt, onion, garlic (satvik, no salt in prasad); 36-hour nirjala vrat on days 2-3",
  "confidence": "computed (Kartik Shukla Chaturthi-Saptami)"
 },
 {
  "id": "cal-017",
  "name": "Dev Uthani / Prabodhini Ekadashi + Tulsi Vivah",
  "community": "Hindu",
  "start": "2026-11-20",
  "end": "2026-11-20",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Fruit, singhara, sweet potato, sabudana; Tulsi vivah sweets, sugarcane, bor",
  "avoided": "Grains, beans, rice, onion, garlic",
  "confidence": "computed (tithi kshaya; some use Nov 21)"
 },
 {
  "id": "cal-018",
  "name": "Devutthana/Prabodhini Ekadashi",
  "community": "Hindu",
  "start": "2026-11-20",
  "end": "2026-11-20",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-019",
  "name": "Guru Nanak Jayanti / Kartik Purnima / Dev Diwali",
  "community": "Sikh",
  "start": "2026-11-24",
  "end": "2026-11-24",
  "kind": "feast",
  "fasting": null,
  "eaten": "Langar (dal, sabzi, roti, kheer, karah prasad)",
  "avoided": "Meat in langar (no non-veg served)",
  "confidence": "computed (Kartik Purnima at sunrise Nov 24)"
 },
 {
  "id": "cal-020",
  "name": "Christmas Advent",
  "community": "Christian",
  "start": "2026-11-29",
  "end": "2026-12-24",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Regular meals; Christmas baking begins (plum cake, kulkuls, rose cookies, marzipan)",
  "avoided": "Some Catholic/Orthodox families abstain from meat on Advent Fridays; Syrian Christians observe 25-day Nombu",
  "confidence": "approx"
 },
 {
  "id": "cal-021",
  "name": "Utpanna Ekadashi",
  "community": "Hindu",
  "start": "2026-12-04",
  "end": "2026-12-04",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-022",
  "name": "Mokshada/Gita Jayanti Ekadashi",
  "community": "Hindu",
  "start": "2026-12-20",
  "end": "2026-12-20",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-023",
  "name": "Christmas Day",
  "community": "Christian",
  "start": "2026-12-25",
  "end": "2026-12-25",
  "kind": "feast",
  "fasting": null,
  "eaten": "Plum cake, appam-stew/duck roast (Kerala), pork vindaloo, sorpotel, bebinca, dodol, kulkuls (Goa), roast chicken, biryani, wine/rum cake",
  "avoided": "",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-024",
  "name": "Saphala Ekadashi",
  "community": "Hindu",
  "start": "2027-01-03",
  "end": "2027-01-03",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-025",
  "name": "Epiphany / Three Kings",
  "community": "Christian",
  "start": "2027-01-06",
  "end": "2027-01-06",
  "kind": "feast",
  "fasting": null,
  "eaten": "Festive meal; Goa Feast of the Three Kings",
  "avoided": "",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-026",
  "name": "Lohri",
  "community": "Sikh/Punjabi Hindu",
  "start": "2027-01-13",
  "end": "2027-01-13",
  "kind": "feast",
  "fasting": null,
  "eaten": "Til, gajak, rewri, peanuts, popcorn, jaggery, sarson saag-makki roti, gur",
  "avoided": "",
  "confidence": "verified-approx"
 },
 {
  "id": "cal-027",
  "name": "Makar Sankranti / Uttarayan / Magh Bihu",
  "community": "Hindu",
  "start": "2027-01-14",
  "end": "2027-01-15",
  "kind": "feast",
  "fasting": null,
  "eaten": "Til-gud ladoo, chikki, khichdi (UP/Bihar), undhiyu-jalebi and chikki (Gujarat), pithe (Assam), puran poli (Maharashtra), tilgul",
  "avoided": "Often vegetarian first day; Magh Bihu feast has non-veg in Assam",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-028",
  "name": "Pongal (Thai Pongal)",
  "community": "Tamil Hindu",
  "start": "2027-01-15",
  "end": "2027-01-15",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sakkarai pongal (jaggery, moong dal, rice, ghee, cashew), ven pongal, sugarcane, vegetable kootu, vadai, payasam",
  "avoided": "Non-veg on festival days (varies)",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-029",
  "name": "Putrada Ekadashi",
  "community": "Hindu",
  "start": "2027-01-19",
  "end": "2027-01-19",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-030",
  "name": "Shab-e-Barat (15 Shaban)",
  "community": "Muslim",
  "start": "2027-01-24",
  "end": "2027-01-25",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Halwa, zarda, sheer, fruit; optional fast next day",
  "avoided": "",
  "confidence": "approx-moon-sighting-dependent"
 },
 {
  "id": "cal-031",
  "name": "Shattila Ekadashi",
  "community": "Hindu",
  "start": "2027-02-02",
  "end": "2027-02-02",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-032",
  "name": "Ramzan (Ramadan)",
  "community": "Muslim",
  "start": "2027-02-08",
  "end": "2027-03-09",
  "kind": "fast",
  "fasting": "ramzan",
  "eaten": "Sehri: dates, paratha/roti, eggs, milk, sheer/seviyan; Iftar: dates, water, fruit chaat, pakora, samosa, haleem (Hyderabad), sherbet, biryani, jalebi",
  "avoided": "Food/water/smoking from fajr to maghrib; heavy fried food at sehri discouraged",
  "confidence": "approx-moon-sighting-dependent (Feb 8 UAE-calculated; India most likely Feb 9; ends Mar 9 or 10)"
 },
 {
  "id": "cal-033",
  "name": "Lent (Great Lent) period",
  "community": "Christian",
  "start": "2027-02-10",
  "end": "2027-03-27",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Fish, vegetarian dishes, simple meals; Friday meatless in Catholic homes",
  "avoided": "Meat on Ash Wednesday and Fridays (Catholic); alcohol/sweets given up by many",
  "confidence": "verified-by-web-for-Ash-Wednesday"
 },
 {
  "id": "cal-034",
  "name": "Vasant Panchami / Saraswati Puja",
  "community": "Hindu",
  "start": "2027-02-11",
  "end": "2027-02-11",
  "kind": "feast",
  "fasting": null,
  "eaten": "Yellow foods: kesari, boondi, sweet saffron rice, khichdi (Bengal bhog with kul chutney)",
  "avoided": "Often no non-veg that day",
  "confidence": "computed"
 },
 {
  "id": "cal-035",
  "name": "Jaya/Bhaimi Ekadashi",
  "community": "Hindu",
  "start": "2027-02-17",
  "end": "2027-02-17",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-036",
  "name": "Vijaya Ekadashi",
  "community": "Hindu",
  "start": "2027-03-03",
  "end": "2027-03-03",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-037",
  "name": "Maha Shivratri",
  "community": "Hindu",
  "start": "2027-03-06",
  "end": "2027-03-06",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Fruit, milk, thandai (bhang optional), sabudana, kuttu, singhara, sweet potato, makhana, potato; sendha namak",
  "avoided": "Grains, onion, garlic, non-veg; night jagran",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-038",
  "name": "Eid al-Fitr",
  "community": "Muslim",
  "start": "2027-03-09",
  "end": "2027-03-10",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sheer khurma, seviyan, biryani, kebabs, korma, phirni, haleem, sheermal, dates",
  "avoided": "Fasting on Eid is forbidden",
  "confidence": "approx-moon-sighting-dependent (Mar 10 more likely in India)"
 },
 {
  "id": "cal-039",
  "name": "Amalaki Ekadashi",
  "community": "Hindu",
  "start": "2027-03-18",
  "end": "2027-03-18",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-040",
  "name": "Holi / Holika Dahan",
  "community": "Hindu",
  "start": "2027-03-21",
  "end": "2027-03-22",
  "kind": "feast",
  "fasting": null,
  "eaten": "Gujiya, malpua, thandai, dahi bhalla, puran poli (Maharashtra), kanji vada, papdi chaat, mathri",
  "avoided": "Many families avoid non-veg; Holika Dahan Mar 21 evening",
  "confidence": "verified-by-web-Holi-Mar-22; Dahan computed"
 },
 {
  "id": "cal-041",
  "name": "Maundy Thursday / Good Friday / Holy Saturday",
  "community": "Christian",
  "start": "2027-03-25",
  "end": "2027-03-27",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Good Friday: fish curry & rice, vegetarian simple meals, hot cross buns; Goan bebinca/sannas after Easter vigil",
  "avoided": "Meat on Good Friday (Catholic); one full meal in strict fasting; Good Friday Mar 26",
  "confidence": "computed (Easter Mar 28, 2027)"
 },
 {
  "id": "cal-042",
  "name": "Easter Sunday",
  "community": "Christian",
  "start": "2027-03-28",
  "end": "2027-03-28",
  "kind": "feast",
  "fasting": null,
  "eaten": "Roast chicken/mutton, appam-stew, pork dishes, easter eggs, cake, sweets (Goa: sorpotel, sannas)",
  "avoided": "",
  "confidence": "verified-standard-computus"
 },
 {
  "id": "cal-043",
  "name": "Papmochani Ekadashi",
  "community": "Hindu",
  "start": "2027-04-02",
  "end": "2027-04-02",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-044",
  "name": "Chaitra Navratri",
  "community": "Hindu",
  "start": "2027-04-07",
  "end": "2027-04-15",
  "kind": "fast",
  "fasting": "navratri",
  "eaten": "Sendha namak (rock salt), kuttu/singhara flour, samak rice, sabudana, makhana, potatoes, sweet potato, pumpkin, lauki, fruit, milk, curd, paneer, peanuts, ghee",
  "avoided": "Grains (wheat, rice, dals), regular salt, onion, garlic, meat, fish, egg, alcohol, (strict) turmeric-free/less spice varies",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-045",
  "name": "Gudi Padwa / Ugadi / Navreh / Sindhi Cheti Chand",
  "community": "Hindu",
  "start": "2027-04-07",
  "end": "2027-04-07",
  "kind": "feast",
  "fasting": null,
  "eaten": "Maharashtra: shrikhand-puri, puran poli, neem-jaggery; Telugu/Kannada: ugadi pachadi (6 tastes), bobbatlu/holige, pulihora; Kashmir Navreh rice plate",
  "avoided": "",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-046",
  "name": "Baisakhi / Vaisakhi / Puthandu / Vishu / Rongali Bihu / Poila Boishakh",
  "community": "Sikh/Punjabi/Tamil/Malayali/Assamese/Bengali",
  "start": "2027-04-14",
  "end": "2027-04-15",
  "kind": "feast",
  "fasting": null,
  "eaten": "Punjab: kada prasad, langar, lassi, chole-bhature; Tamil Puthandu: mango pachadi, vadai, payasam; Vishu sadya, kani; Bihu: pitha, laru, duck/chicken curry; Poila Boishakh: panta-ilish, mishti",
  "avoided": "",
  "confidence": "verified-approx (Baisakhi Apr 14; Poila Boishakh Apr 15; some sites list Apr 7 incorrectly)"
 },
 {
  "id": "cal-047",
  "name": "Ram Navami",
  "community": "Hindu",
  "start": "2027-04-15",
  "end": "2027-04-15",
  "kind": "fast",
  "fasting": "navratri",
  "eaten": "Fruit, sabudana, kuttu/samak, panakam, kosambari, sunnundalu",
  "avoided": "Grains, onion, garlic, non-veg (many)",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-048",
  "name": "Kamada Ekadashi",
  "community": "Hindu",
  "start": "2027-04-17",
  "end": "2027-04-17",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-049",
  "name": "Mahavir Jayanti",
  "community": "Jain",
  "start": "2027-04-19",
  "end": "2027-04-19",
  "kind": "feast",
  "fasting": null,
  "eaten": "Satvik vegetarian, no root vegetables, in strict Jain homes",
  "avoided": "Onion, garlic, potato, all roots, non-veg",
  "confidence": "computed"
 },
 {
  "id": "cal-050",
  "name": "Hanuman Jayanti",
  "community": "Hindu",
  "start": "2027-04-20",
  "end": "2027-04-20",
  "kind": "feast",
  "fasting": null,
  "eaten": "Boondi ladoo, churma, sweets as prasad; Tuesday/Saturday satvik meals",
  "avoided": "Non-veg and onion-garlic for many devotees",
  "confidence": "computed"
 },
 {
  "id": "cal-051",
  "name": "Varuthini Ekadashi",
  "community": "Hindu",
  "start": "2027-05-02",
  "end": "2027-05-02",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-052",
  "name": "Akshaya Tritiya",
  "community": "Hindu",
  "start": "2027-05-09",
  "end": "2027-05-09",
  "kind": "feast",
  "fasting": null,
  "eaten": "Mango dishes, aamras-puri, sattu, kheer, ripe mango, kharbooja, watermelon; Jain Varsitap parana with sugarcane juice",
  "avoided": "",
  "confidence": "computed"
 },
 {
  "id": "cal-053",
  "name": "Eid al-Adha (Bakrid)",
  "community": "Muslim",
  "start": "2027-05-16",
  "end": "2027-05-17",
  "kind": "feast",
  "fasting": null,
  "eaten": "Mutton biryani, korma, kebab, qurbani meat, sheer khurma, haleem",
  "avoided": "Eating before Eid prayers (sunnah); Arafah fast (optional) on preceding day",
  "confidence": "approx-moon-sighting-dependent (May 16 UAE; India likely May 17)"
 },
 {
  "id": "cal-054",
  "name": "Mohini Ekadashi",
  "community": "Hindu",
  "start": "2027-05-16",
  "end": "2027-05-16",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-055",
  "name": "Buddha Purnima / Vesak",
  "community": "Buddhist",
  "start": "2027-05-20",
  "end": "2027-05-20",
  "kind": "feast",
  "fasting": null,
  "eaten": "Kheer (Sujata offering), vegetarian meals",
  "avoided": "Meat and alcohol (many observers)",
  "confidence": "computed"
 },
 {
  "id": "cal-056",
  "name": "Apara Ekadashi",
  "community": "Hindu",
  "start": "2027-06-01",
  "end": "2027-06-01",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-057",
  "name": "Muharram / Ashura",
  "community": "Muslim",
  "start": "2027-06-06",
  "end": "2027-06-16",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Khichda / haleem, sherbet sabeel, fruit, water; optional fast on 9th-10th Muharram",
  "avoided": "Celebratory food; Shia observe mourning",
  "confidence": "approx-moon-sighting-dependent (Ashura Jun 15 or 16)"
 },
 {
  "id": "cal-058",
  "name": "Nirjala Ekadashi",
  "community": "Hindu",
  "start": "2027-06-14",
  "end": "2027-06-14",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-059",
  "name": "Yogini Ekadashi",
  "community": "Hindu",
  "start": "2027-06-30",
  "end": "2027-06-30",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-060",
  "name": "Rath Yatra (Puri)",
  "community": "Odia",
  "start": "2027-07-06",
  "end": "2027-07-06",
  "kind": "feast",
  "fasting": null,
  "eaten": "Mahaprasad, khechedi, dalma, sweets, gaja, pana",
  "avoided": "",
  "confidence": "computed (approx)"
 },
 {
  "id": "cal-061",
  "name": "Jain Chaturmas begins",
  "community": "Jain",
  "start": "2027-07-14",
  "end": "2027-11-10",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Dry, fresh, simple foods; green leafy vegetables, sprouts and figs avoided by many; boiled water",
  "avoided": "Green leafy vegetables, brinjal, dried fruits (strict), root vegetables (always), after-sunset eating",
  "confidence": "approx (Devshayani to Dev Uthani Ekadashi)"
 },
 {
  "id": "cal-062",
  "name": "Devshayani/Ashadhi Ekadashi",
  "community": "Hindu",
  "start": "2027-07-14",
  "end": "2027-07-14",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-063",
  "name": "Guru Purnima",
  "community": "Hindu",
  "start": "2027-07-18",
  "end": "2027-07-18",
  "kind": "feast",
  "fasting": null,
  "eaten": "Satvik prasad, kheer",
  "avoided": "",
  "confidence": "computed"
 },
 {
  "id": "cal-064",
  "name": "Shravan Mondays (North India, Purnimanta Sawan)",
  "community": "Hindu",
  "start": "2027-07-19",
  "end": "2027-08-16",
  "kind": "fast",
  "fasting": "shravan",
  "eaten": "Fruit, milk, sabudana, kuttu, singhara, makhana, potato, sendha namak (Mondays); Sawan also satvik",
  "avoided": "Non-veg, onion, garlic (many families the whole month); grains on fast days",
  "confidence": "computed"
 },
 {
  "id": "cal-065",
  "name": "Kamika Ekadashi",
  "community": "Hindu",
  "start": "2027-07-29",
  "end": "2027-07-29",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-066",
  "name": "Shravan Mondays (Maharashtra/Gujarat/South, Amanta Shravan)",
  "community": "Hindu",
  "start": "2027-08-09",
  "end": "2027-08-30",
  "kind": "fast",
  "fasting": "shravan",
  "eaten": "Single meal: sabudana khichdi, bhagar, fruits, milk; Maharashtra Shravan Mondays: shivamut, jwari/rajgira",
  "avoided": "Non-veg, onion, garlic through the month (many)",
  "confidence": "computed (Amanta month Aug 3 - Sep 1)"
 },
 {
  "id": "cal-067",
  "name": "Shravana Putrada/Pavitra Ekadashi",
  "community": "Hindu",
  "start": "2027-08-12",
  "end": "2027-08-12",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-068",
  "name": "Raksha Bandhan / Narali Purnima",
  "community": "Hindu",
  "start": "2027-08-17",
  "end": "2027-08-17",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sweets (ghewar, ladoo, kheer), nariyal bhaat/narali bhat (Maharashtra coastal)",
  "avoided": "Non-veg in many homes",
  "confidence": "computed"
 },
 {
  "id": "cal-069",
  "name": "Janmashtami",
  "community": "Hindu",
  "start": "2027-08-25",
  "end": "2027-08-25",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Day: fruit, sabudana, kuttu, milk, makhana; Midnight: panjiri, makhan-mishri, kheer, dahi, panchamrit, gopalkala (Maharashtra)",
  "avoided": "Grains, onion, garlic",
  "confidence": "verified-by-web-(Aug 25 per web, matches Krishna Ashtami computation)"
 },
 {
  "id": "cal-070",
  "name": "Paryushan Parva (Shwetambar) ending in Samvatsari",
  "community": "Jain",
  "start": "2027-08-27",
  "end": "2027-09-03",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Upvas, ayambil, boiled water only; Samvatsari: pratikraman, forgiveness; fasts of 8 days for some",
  "avoided": "Roots, onion, garlic, green leafy vegetables, brinjal, after-sunset eating, sprouts (many)",
  "confidence": "verified-by-web-(Aug 27 - Sep 3 per web)"
 },
 {
  "id": "cal-071",
  "name": "Aja Ekadashi",
  "community": "Hindu",
  "start": "2027-08-28",
  "end": "2027-08-28",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-072",
  "name": "Hartalika Teej",
  "community": "Hindu",
  "start": "2027-09-03",
  "end": "2027-09-03",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Break fast next day with sweets, dry fruits, kheer",
  "avoided": "Water and food (nirjala) by many",
  "confidence": "computed (approx)"
 },
 {
  "id": "cal-073",
  "name": "Ganesh Chaturthi",
  "community": "Hindu",
  "start": "2027-09-04",
  "end": "2027-09-04",
  "kind": "feast",
  "fasting": null,
  "eaten": "Modak (ukdiche/fried), puran poli, karanji, panchakhadya, shrikhand, varan-bhat-toop, sheera, motichoor ladoo",
  "avoided": "Non-veg on the day (most families), onion-garlic in naivedya",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-074",
  "name": "Das Lakshan (Digambar Paryushan)",
  "community": "Jain",
  "start": "2027-09-05",
  "end": "2027-09-14",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Single meal, ayambil, boiled water, sattvic food; ten virtues",
  "avoided": "Roots, onion, garlic, green vegetables, after sunset (many)",
  "confidence": "computed (Bhadrapad Shukla Panchami to Chaturdashi)"
 },
 {
  "id": "cal-075",
  "name": "Parivartini Ekadashi",
  "community": "Hindu",
  "start": "2027-09-11",
  "end": "2027-09-11",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Fruit, sabudana, makhana",
  "avoided": "Grains, onion, garlic",
  "confidence": "computed"
 },
 {
  "id": "cal-076",
  "name": "Parivartini/Parsva Ekadashi",
  "community": "Hindu",
  "start": "2027-09-11",
  "end": "2027-09-11",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-077",
  "name": "Onam / Thiruvonam",
  "community": "Malayali Hindu",
  "start": "2027-09-12",
  "end": "2027-09-12",
  "kind": "feast",
  "fasting": null,
  "eaten": "Sadya on banana leaf: rice, parippu, sambar, avial, olan, thoran, kalan, pachadi, pulissery, injipuli, pickle, papadam, payasam (palada, pradhaman)",
  "avoided": "Non-veg on Thiruvonam day for most; Christian Kerala households enjoy fish/meat on other days",
  "confidence": "verified-by-web"
 },
 {
  "id": "cal-078",
  "name": "Pitru Paksha",
  "community": "Hindu",
  "start": "2027-09-17",
  "end": "2027-10-01",
  "kind": "mixed",
  "fasting": "custom",
  "eaten": "Satvik meals, kheer, puri, lauki, arbi",
  "avoided": "Onion, garlic, non-veg",
  "confidence": "approx (Sep 16/17 - Sarvapitri Amavasya Sep 30)"
 },
 {
  "id": "cal-079",
  "name": "Indira Ekadashi",
  "community": "Hindu",
  "start": "2027-09-26",
  "end": "2027-09-26",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-080",
  "name": "Sharad Navratri 2027",
  "community": "Hindu",
  "start": "2027-10-01",
  "end": "2027-10-09",
  "kind": "fast",
  "fasting": "navratri",
  "eaten": "Sendha namak (rock salt), kuttu/singhara flour, samak rice, sabudana, makhana, potatoes, sweet potato, pumpkin, lauki, fruit, milk, curd, paneer, peanuts, ghee",
  "avoided": "Grains (wheat, rice, dals), regular salt, onion, garlic, meat, fish, egg, alcohol, (strict) turmeric-free/less spice varies",
  "confidence": "approx-(computed; pratipada tithi at sunrise may need verification Oct 1)"
 },
 {
  "id": "cal-081",
  "name": "Papankusha Ekadashi",
  "community": "Hindu",
  "start": "2027-10-11",
  "end": "2027-10-11",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-082",
  "name": "Karva Chauth 2027",
  "community": "Hindu",
  "start": "2027-10-18",
  "end": "2027-10-18",
  "kind": "fast",
  "fasting": "custom",
  "eaten": "Sargi pre-dawn; evening dinner after moonrise",
  "avoided": "Food and water until moonrise",
  "confidence": "computed (Krishna Chaturthi at moonrise Oct 18)"
 },
 {
  "id": "cal-083",
  "name": "Rama Ekadashi",
  "community": "Hindu",
  "start": "2027-10-25",
  "end": "2027-10-25",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-084",
  "name": "Diwali 2027 (Lakshmi Puja)",
  "community": "Hindu",
  "start": "2027-10-29",
  "end": "2027-10-29",
  "kind": "feast",
  "fasting": null,
  "eaten": "Mithai, chakli, chivda, karanji, puri-sabzi",
  "avoided": "Non-veg in most homes",
  "confidence": "computed (Amavasya at pradosh Oct 29)"
 },
 {
  "id": "cal-085",
  "name": "Devutthana/Prabodhini Ekadashi",
  "community": "Hindu",
  "start": "2027-11-10",
  "end": "2027-11-10",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-086",
  "name": "Guru Nanak Jayanti 2027",
  "community": "Sikh",
  "start": "2027-11-14",
  "end": "2027-11-14",
  "kind": "feast",
  "fasting": null,
  "eaten": "Langar, kada prasad",
  "avoided": "Non-veg in langar",
  "confidence": "computed (Kartik Purnima)"
 },
 {
  "id": "cal-087",
  "name": "Utpanna Ekadashi",
  "community": "Hindu",
  "start": "2027-11-24",
  "end": "2027-11-24",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-088",
  "name": "Mokshada/Gita Jayanti Ekadashi",
  "community": "Hindu",
  "start": "2027-12-09",
  "end": "2027-12-09",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-089",
  "name": "Saphala Ekadashi",
  "community": "Hindu",
  "start": "2027-12-23",
  "end": "2027-12-23",
  "kind": "fast",
  "fasting": "ekadashi",
  "eaten": "Phalahar: fruit, milk, curd, sabudana, kuttu/singhara, samak rice, makhana, potato, sweet potato, sendha namak; nirjala/fruit-only for strict",
  "avoided": "Rice, wheat, dals/beans, regular salt, onion, garlic, non-veg; parana (break) next morning after sunrise within Dwadashi",
  "confidence": "computed (tithi at Delhi sunrise; +/-1 day by sect and city: Smarta vs Vaishnava)"
 },
 {
  "id": "cal-090",
  "name": "Christmas 2027",
  "community": "Christian",
  "start": "2027-12-25",
  "end": "2027-12-25",
  "kind": "feast",
  "fasting": null,
  "eaten": "Plum cake, kulkuls, bebinca, roast, appam-stew, biryani",
  "avoided": "",
  "confidence": "verified-by-web"
 }
] as Festival[];

const iso = (t: number, tz: number) => new Date(t + tz * 60_000).toISOString().slice(0, 10);

/** Festivals and fasts on the local day containing `t`. */
export function festivalsOn(t: number, tzOffsetMin = 330): Festival[] {
  const d = iso(dayStart(t, tzOffsetMin) + 12 * 3_600_000, tzOffsetMin);
  return FESTIVALS.filter((f) => f.start <= d && d <= f.end);
}
