import type { Allergen, Diet, Food, MealSlot } from './types';

/** Regional dishes added after persona testing (Kerala, Goa, Bihar, Rajasthan, Karnataka, Maharashtra, Gujarat, Parsi, Kashmir). Each has its own steps. */
type Row = [id: string, name: string, cuisine: string, slots: string, diet: Diet, tags: string, allergens: Allergen[], prep: number, spice: 0 | 1 | 2 | 3, kcal: number, protein: number, fibre: number, water: number, ingredients: string, steps: string[]];
const S: Record<string, MealSlot> = { B: 'breakfast', L: 'lunch', D: 'dinner', S: 'snack' };

const ROWS: Row[] = [
  ['appam-egg-roast', 'Appam with egg roast', 'kerala', 'B D', 'vegetarian', 'warm comfort high-protein', ['egg'], 40, 2, 560, 22, 4, 120, 'rice, coconut, eggs, onion, tomatoes, ginger, garlic, coconut oil, curry leaves, black pepper', ['Grind soaked rice, 1/4 cup coconut and a pinch of yeast and sugar to a smooth batter. Rest 6 hours.', 'Hard-boil 4 eggs for 9 minutes, peel and halve.', 'Soften 2 sliced onions in coconut oil with ginger, garlic and curry leaves. Add 2 chopped tomatoes, 1 tsp pepper and cook until pulpy.', 'Add the eggs and a splash of water, simmer 5 minutes.', 'Swirl a ladle of batter in a hot appam pan, cover 2 minutes. Serve the lacy appams with the egg roast.']],
  ['fish-molee', 'Kerala fish molee with rice', 'kerala', 'L D', 'pescatarian', 'warm gentle high-protein', ['fish'], 35, 1, 560, 30, 3, 250, 'fish, coconut milk, onion, ginger, garlic, green chilli, tomatoes, turmeric, rice, coconut oil, curry leaves', ['Marinate 300 g fish pieces in 1/2 tsp turmeric and salt for 10 minutes.', 'Heat 1 tbsp coconut oil, soften 1 sliced onion with ginger, garlic, green chilli and curry leaves without browning.', 'Add 1/2 tsp turmeric, 1 cup thin coconut milk and bring to a gentle simmer.', 'Slide in the fish and cook 8 minutes until it flakes. Do not stir hard.', 'Stir in 1/2 cup thick coconut milk and one chopped tomato, warm through and serve with rice.']],
  ['thoran-rice', 'Cabbage thoran with rice and parippu', 'kerala', 'L D', 'vegan', 'warm gentle fibre low-sodium', [], 30, 1, 480, 14, 9, 200, 'cabbage, coconut, mustard seeds, curry leaves, green chilli, turmeric, rice, moong dal, coconut oil, garlic', ['Pressure cook 1/2 cup moong dal with turmeric and salt for 3 whistles, mash lightly, and temper with mustard seeds in coconut oil.', 'Finely shred 2 cups cabbage.', 'Heat 1 tbsp coconut oil, splutter 1 tsp mustard seeds, add curry leaves, 1 chopped green chilli and 2 garlic cloves.', 'Add the cabbage, 1/4 tsp turmeric and salt, cover and cook 5 minutes.', 'Fold in 1/4 cup grated coconut, cook 2 minutes. Serve with hot rice and the dal.']],
  ['olan-rice', 'Olan with rice', 'kerala', 'L D', 'vegan', 'warm gentle light low-gi', [], 30, 0, 430, 9, 7, 300, 'ash gourd, black-eyed peas, coconut milk, green chilli, ginger, coconut oil, curry leaves, rice', ['Soak 1/4 cup black-eyed peas for 2 hours and boil until soft, about 20 minutes.', 'Cut 2 cups ash gourd into thin pieces.', 'Cook the gourd with 2 slit green chillies, ginger and salt in a little water for 8 minutes until translucent.', 'Add the peas and 3/4 cup thin coconut milk, simmer 3 minutes.', 'Turn off the heat, stir in 1/4 cup thick coconut milk and a spoon of coconut oil, add curry leaves. Serve with rice.']],
  ['kerala-parotta-salna', 'Kerala parotta with vegetable salna', 'kerala', 'D', 'vegan', 'warm comfort festive high-gi fried', ['gluten'], 45, 2, 700, 14, 6, 150, 'maida, oil, onion, tomatoes, garlic, ginger, potatoes, carrots, coconut, fennel seeds, garam masala', ['Knead 2 cups maida with salt, sugar, oil and water into a soft dough. Rest 2 hours.', 'Divide into balls, roll thin, pleat and coil, then flatten and cook on a hot tawa with oil until golden.', 'For the salna, grind 3 tbsp coconut with 1/2 tsp fennel seeds to a paste.', 'Soften onion, garlic and ginger in oil, add tomato, diced potato and carrot, 1/2 tsp garam masala and 1 cup water. Cook 12 minutes.', 'Stir in the coconut paste and simmer 5 minutes. Crush the parotta and serve with the salna.']],
  ['malabar-chicken-biryani', 'Malabar chicken biryani', 'kerala', 'L D', 'omnivore', 'warm festive comfort high-gi high-protein high-sodium high-purine', ['dairy'], 80, 2, 760, 34, 3, 150, 'basmati rice, chicken, onion, garlic, ginger, tomatoes, curd, ghee, green chilli, mint, coriander, garam masala, cashews, raisins', ['Marinate 400 g chicken in curd, ginger-garlic paste, garam masala and salt for 30 minutes.', 'Fry 3 sliced onions in ghee until golden; keep half for layering. Add tomato and the chicken, cook covered 15 minutes until no pink remains and the juices run clear.', 'Par-boil 1.5 cups soaked basmati until 70 percent cooked.', 'Layer rice over the chicken with fried onions, mint, coriander, cashews and raisins. Seal and cook on dum for 20 minutes on low heat.', 'Rest 10 minutes, then mix gently from the bottom. Serve with raita.']],
  ['beef-ulathiyathu', 'Kerala beef ulathiyathu with parotta', 'kerala', 'D', 'omnivore', 'warm festive comfort high-protein high-purine high-sodium', ['gluten'], 90, 3, 740, 38, 3, 100, 'beef, coconut, onion, garlic, ginger, curry leaves, black pepper, fennel seeds, maida, coconut oil, turmeric', ['Pressure cook 400 g beef cubes with turmeric, salt, ginger and garlic for 8 to 10 whistles until tender.', 'In coconut oil fry sliced coconut pieces until golden, then add curry leaves, 2 sliced onions, 1 tsp pepper and 1 tsp fennel.', 'Add the beef with its stock and simmer uncovered until the gravy is dry and dark, about 20 minutes.', 'Make or warm 2 parotta and serve together.']],
  ['neer-dosa-chutney', 'Neer dosa with coconut chutney', 'karnataka', 'B', 'vegan', 'warm gentle light', [], 25, 1, 300, 5, 3, 200, 'rice, coconut, green chilli, ginger, coconut oil, curry leaves', ['Soak 1 cup rice for 3 hours and grind with 1/4 cup coconut to a very thin batter with salt.', 'Heat a non-stick tawa and pour a ladle of the thin batter, swirling to cover.', 'Cover and cook 1 minute, no flipping, then fold.', 'Blend coconut with green chilli, ginger and salt for the chutney and serve.']],
  ['zunka-bhakar', 'Zunka with jowar bhakri', 'maharashtrian', 'L D', 'vegan', 'warm comfort fibre low-gi iron', [], 30, 2, 440, 14, 9, 100, 'besan, onion, garlic, green chilli, mustard seeds, jowar flour, oil, coriander, turmeric', ['Knead jowar flour with hot water into a soft dough and pat out bhakris on a hot tawa, finishing over the flame.', 'Temper mustard seeds, then fry chopped onion, garlic and green chilli until golden.', 'Add 1/2 tsp turmeric, then stir in 1/2 cup besan and cook 3 minutes, sprinkling water until crumbly.', 'Cover 5 minutes, garnish with coriander and serve with the bhakri.']],
  ['dhansak-rice', 'Parsi dhansak with caramelised rice', 'parsi', 'L D', 'omnivore', 'warm festive comfort high-protein fibre', [], 75, 2, 700, 38, 10, 250, 'chicken, toor dal, masoor dal, pumpkin, brinjal, onion, garlic, ginger, tomatoes, rice, sugar, dhansak masala, tamarind', ['Pressure cook the dals with pumpkin and brinjal until soft and blend smooth.', 'Brown onion, ginger and garlic, add tomatoes and 2 tbsp dhansak masala, then 400 g chicken and cook until no pink remains.', 'Add the blended dal, tamarind pulp and salt, simmer 15 minutes.', 'Caramelise 1 tbsp sugar in a pan, add 1 cup rice and 2 cups water, and cook until fluffy. Serve with the dhansak.']],
];

function dish(r: Row): Food {
  const [id, name, cuisine, slots, diet, tags, allergens, prepMin, spice, kcal, proteinG, fibreG, waterMl, ingredients, steps] = r;
  return { id, name, cuisine, spice, diet, slots: slots.split(' ').map((s) => S[s]!) as MealSlot[], tags: tags.split(' '), allergens, prepMin, nutrients: { kcal, proteinG, fibreG, waterMl }, ingredients: ingredients.split(', '), steps };
}

export const INDIA_REGIONAL: Food[] = ROWS.map(dish);
