#!/usr/bin/env node
// Brings the GitHub issues in line with docs/tickets/tickets.json: ticks the
// acceptance criteria of finished tasks, closes them, and updates each epic's
// checklist (closing the epic when all of its tasks are done).
//
//   node scripts/sync-issues.mjs            # apply
//   node scripts/sync-issues.mjs --dry-run  # show what would change
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const dry = process.argv.includes('--dry-run');
const { repo, epics } = JSON.parse(readFileSync(new URL('../docs/tickets/tickets.json', import.meta.url), 'utf8'));

function api(method, path, body) {
  const args = ['api', '--method', method, `repos/${repo}/${path}`, ...(body ? ['--input', '-'] : [])];
  const out = execFileSync('gh', args, { input: body ? JSON.stringify(body) : undefined, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  return out ? JSON.parse(out) : {};
}

const issues = [];
for (let page = 1; ; page++) {
  const batch = api('GET', `issues?state=all&per_page=100&page=${page}`).filter?.((i) => !i.pull_request) ?? [];
  issues.push(...batch);
  if (batch.length < 100) break;
}
const byTitle = (prefix) => issues.find((i) => i.title.startsWith(prefix));

let changed = 0;
// Some setups append an attribution footer to issue bodies. Keep whatever footer is there and
// compare without it, so only real content changes count.
const FOOTER = /\n\n---\n_Generated by[\s\S]*$/;
function update(issue, content, state, title) {
  const current = issue.body ?? '';
  const footer = current.match(FOOTER)?.[0] ?? '';
  const patch = {};
  if (current.replace(FOOTER, '') !== content) patch.body = content + footer;
  if (title && issue.title !== title) patch.title = title;
  if (state && issue.state !== state) Object.assign(patch, { state, ...(state === 'closed' ? { state_reason: 'completed' } : {}) });
  if (!Object.keys(patch).length) return;
  changed += 1;
  console.log(`${dry ? 'would update' : 'updating'} #${issue.number} ${issue.title}${patch.state ? ` -> ${patch.state}` : ''}`);
  if (!dry) api('PATCH', `issues/${issue.number}`, patch);
}

for (const e of epics) {
  const rows = [];
  for (const t of e.tasks) {
    const issue = byTitle(`[${t.key}] `);
    if (!issue) {
      // A ticket added after the first run: create its issue and attach it to the epic.
      console.log(`${dry ? 'would create' : 'creating'} [${t.key}] ${t.title}`);
      changed += 1;
      if (dry) continue;
      const body = [`Part of **${e.title}**, sprint ${t.sprint}.`, '', '### Acceptance criteria', ...t.acceptance.map((a) => `- [${t.status === 'done' ? 'x' : ' '}] ${a}`), '', 'Plan: `docs/PLAN.md`'].join('\n');
      const created = api('POST', 'issues', { title: `[${t.key}] ${t.title}`, body, labels: ['task', `phase-${e.key.slice(1)}`, `sprint-${t.sprint}`, `area:${t.area}`] });
      issues.push(created);
      const epicIssue = byTitle(`[Epic] ${e.title}`);
      try {
        if (epicIssue) api('POST', `issues/${epicIssue.number}/sub_issues`, { sub_issue_id: created.id });
      } catch {
        // sub-issues unavailable; the epic checklist still links it
      }
      rows.push({ t, issue: created });
      continue;
    }
    const done = t.status === 'done';
    const body = [`Part of **${e.title}**, sprint ${t.sprint}.`, '', '### Acceptance criteria', ...t.acceptance.map((a) => `- [${done ? 'x' : ' '}] ${a}`), '', 'Plan: `docs/PLAN.md`'].join('\n');
    update(issue, body, done ? 'closed' : 'open', `[${t.key}] ${t.title}`);
    rows.push({ t, issue });
  }
  const epic = byTitle(`[Epic] ${e.title}`);
  if (!epic) continue;
  const sprints = [...new Set(e.tasks.map((t) => t.sprint))];
  const body = [
    e.summary,
    '',
    ...sprints.flatMap((s) => [`### Sprint ${s}`, ...rows.filter((r) => r.t.sprint === s).map((r) => `- [${r.t.status === 'done' ? 'x' : ' '}] #${r.issue.number} ${r.t.key} ${r.t.title}`), '']),
    'Plan: `docs/PLAN.md`',
  ].join('\n');
  update(epic, body, e.tasks.every((t) => t.status === 'done') ? 'closed' : 'open');
}
console.log(changed ? `${dry ? 'Would change' : 'Changed'} ${changed} issues.` : 'Issues already match the ticket file.');
